version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "17:00"
  open-pull-requests-limit: 10
  versioning-strategy: lockfile-only
  ignore:
  - dependency-name: elliptic
    versions:
    - 6.5.4
  - dependency-name: "@storybook/cli"
    versions:
    - 6.1.11
    - 6.1.15
    - 6.1.20
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.11.1
    - 4.14.1
    - 4.15.2
  - dependency-name: "@storybook/react"
    versions:
    - 6.1.11
    - 6.1.15
    - 6.1.20
  - dependency-name: eslint
    versions:
    - 7.16.0
    - 7.19.0
    - 7.21.0
  - dependency-name: "@babel/core"
    versions:
    - 7.12.10
    - 7.13.8
  - dependency-name: "@testing-library/react"
    versions:
    - 11.2.2
    - 11.2.3
  - dependency-name: husky
    versions:
    - 4.3.6
    - 4.3.8
  - dependency-name: yalc
    versions:
    - 1.0.0-pre.49
    - 1.0.0-pre.50
  - dependency-name: nested-object-assign
    versions:
    - 1.0.4
  - dependency-name: ini
    versions:
    - 1.3.8
  - dependency-name: node-notifier
    versions:
    - 8.0.1
  - dependency-name: semantic-release
    versions:
    - 17.2.3
  - dependency-name: npm-user-validate
    versions:
    - 1.0.1
  - dependency-name: "@commitlint/config-conventional"
    versions:
    - 11.0.0
