trigger:
    branches:
        include:
            - master

jobs:
    - job: Build_and_Release_Package
      displayName: Build and Release Package
      condition: not(contains(variables['Build.SourceBranch'], 'tag'))
      steps:
          - task: NodeTool@0
            displayName: 'Use Node 10.x'
            inputs:
                versionSpec: 10.x

          - script: npm install
            displayName: Install dependencies

          - script: npm run build
            displayName: Build Package

          - script: npm run test
            displayName: Unit Tests

          - script: npm run semantic-release
            displayName: Version and Tag
            env:
                GH_TOKEN: $(gh.token)
                NPM_TOKEN: $(npm.token)
