trigger:
    branches:
        include:
            - master

jobs:
    - job: Build_and_Release_Package
      displayName: Build and Release Package
      condition: not(contains(variables['Build.SourceBranch'], 'tag'))
      steps:
          - task: NodeTool@0
            displayName: 'Use Node 10.x'
            inputs:
                versionSpec: 10.x

          - script: yarn install
            displayName: Install dependencies

          - script: yarn build
            displayName: Build Package

          - script: yarn test
            displayName: Unit Tests

          - task: PublishTestResults@2
            condition: succeededOrFailed()
            inputs:
                testRunner: JUnit
                testResultsFiles: 'TEST-RESULTS.xml'

          - script: yarn semantic-release
            displayName: Version and Tag
            env:
                GH_TOKEN: $(gh.token)
                yarn_TOKEN: $(yarn.token)
