trigger:
    branches:
        include:
            - master

jobs:
    - job: Version_And_Tag
      displayName: Version and Tag
      condition: not(contains(variables['Build.SourceBranch'], 'tag'))
      steps:
          - task: NodeTool@0
            displayName: 'Use Node 10.x'
            inputs:
                versionSpec: 10.x

          - script: npm install
            displayName: Install dependencies

          - script: npm run semantic-release
            displayName: Version and Tag
            env:
                GH_TOKEN: $(gh.token)
                NPM_TOKEN: $(npm.token)
